---
title: "sfp-tables"
author: "Nima Dahir"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
# This script generates all results in "Who Owns the Neighborhood? Ethnoracial Composition of Property Ownership and Neighborhood Trajectories in San Francisco" 

knitr::opts_chunk$set(warning = FALSE, message = FALSE) 

#Clean up environment
rm(list=ls())

#Packages
library(kableExtra)
library(stargazer)
library(ggplot2)
library(foreign)
library(tidycensus)
library(janitor)
library(tidyverse)
library(nnet)
library(data.table)
library(psych)
library(plm)
library(conflicted)
library(hrbrthemes)

# Maps Packages:
library(patchwork) # For combining plots
library(scales)
library(sf)
library(ggmap)
library(tigris)

```

# Load Data

```{r data}
df <- read_csv(here::here("df_full.csv")) 

```

# Tables
## Table 1: Racial Compositions of Owners and Residents by Divergence

```{r table1}
  df %>% 
  mutate(divergence_quartile = ntile(divergence,4)) %>% # higher divergence, higher quartile
  dplyr::select(divergence_quartile,
                asian_share, # _shares are owner shares
                nhblk_share,
                hisp_share,
                nhwht_share,
                other_share,
                pnhwht, # resident shares
                pnhblk,
                phisp,
                pasian,
                pother) %>% 
  group_by(divergence_quartile) %>% 
  summarise(across(where(is.numeric),list(mean = mean)))
```

## Table 2: Descriptive Statistics of Neighborhood Characteristics in Dataset

```{r table 2}

table2 <- df %>% 
  select(year_num,
         hinc,
         pcol,
         punemp,
         pprof,
         pnhblk,
         pnhwht,
         pasian,
         phisp,
         mrent,
         pown,
         p30old,
         p10yrs,
         mhmval,
         divergence) %>% 
  group_by(year_num) %>%
  summarise(across(
    everything(),
    list(
      mean = ~mean(., na.rm = TRUE),
      sd = ~sd(., na.rm = TRUE)
    )
  ))

```

## Table 3: Divergence Score and Race Models

```{r table3}

# Begin by scaling divergence to interpret in standard deviations

scaled <- df %>% 
  group_by(year) %>% 
  mutate(across(where(is.numeric), ~ as.numeric(scale(.))))

# Divergence Cross-Sectional Models:
m1 <- plm(divergence ~ pnhblk + phisp + pasian + INDIVIDUAL + pown, model="within",index=c("trtid10","year"), effect = "time", data=scaled)

m2 <- plm(divergence ~ pnhblk + phisp + pasian + hinc + pop + pown + pvac + p30old + INDIVIDUAL, model="within",index=c("trtid10","year"), effect = "time", data=scaled)

# Foreign born:
m3 <- plm(divergence ~ pfb + pown + INDIVIDUAL, model="within",index=c("trtid10","year"), effect = "time", data=scaled)

m4 <-plm(divergence ~ pfb + pnhblk + phisp + hinc + pop + pown + pvac + p30old + INDIVIDUAL, model="within",index=c("trtid10","year"), effect = "time", data=scaled)

# Asian:
m5 <- plm(divergence ~ pasian +
            hinc + pop + pown  + pvac + p30old + INDIVIDUAL, model="within",index=c("trtid10","year"), effect = "time", data=scaled)

# Divergence Cross-Sectional Model with Interactions

m6 <- plm(divergence ~ pnhblk*pfb + phisp*pfb + 
                     hinc + pop + pown  + pvac + p30old + INDIVIDUAL, model="within",index=c("trtid10","year"), effect = "time", data=scaled)

stargazer(m1,m2,m3,m4,m5,m6,
                    type = "text",
                    omit = c("factor\\(year", "factor\\(trtid10", "Constant", "INDIVIDUAL"),
                    header = FALSE,
                    no.space = TRUE,
                    dep.var.labels = "Divergence Score",
                    title = "Race, Foreign Born",
                    keep.stat = c("n","rsq"),
                    notes = c("All models include year fixed effects and control for the number of individually-owned properties in each tract.","All variables are standardized to a mean of zero and standard deviation of 1; thus, coefficients can be interpreted as expected standard deviation changes in divergence with one standard deviation change in each independent variable."),
                    notes.align = "l",
                    star.cutoffs = c(0.05, 0.01, 0.001))
```


## Table 4: Divergence and Neighborhood Change

```{r table4}

library(plm)

# Create Analytic Sample for these models:
ses <- scaled %>% 
  filter(!is.na(pcol) & !is.na(punemp) & !is.na(ppov) & !is.na(hinc) & !is.na(pprof)) %>% 
  filter(!is.na(mrent) & !is.na(pown) & !is.na(p30old) & !is.na(p10yrs) & !is.na(pvac) & !is.na(mhmval)) 


# Panel 1: SES Variables
ses1 <- plm(pcol ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pnhblk) + plm::lag(phisp) + plm::lag(pasian) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")
ses2 <- plm(punemp ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pnhblk) + plm::lag(phisp) + plm::lag(pasian) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")
ses3 <- plm(ppov ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pnhblk) + plm::lag(phisp) + plm::lag(pasian) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")
ses4 <- plm(hinc ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pnhblk) + plm::lag(phisp) + plm::lag(pasian) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")
ses5 <- plm(pprof ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pnhblk) + plm::lag(phisp) + plm::lag(pasian) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")

# Panel 2: Housing Variables

h1 <- plm(mrent ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pnhblk) + plm::lag(phisp) + plm::lag(pasian) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")
h2 <- plm(pown ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pnhblk) + plm::lag(phisp) + plm::lag(pasian) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")
h3 <- plm(p30old ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pnhblk) + plm::lag(phisp) + plm::lag(pasian) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")
h4 <- plm(p10yrs ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pnhblk) + plm::lag(phisp) + plm::lag(pasian) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")
h5 <- plm(mhmval ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pnhblk) + plm::lag(phisp) + plm::lag(pasian) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")

# Panel 3: Race

r8 <- plm(pnhwht ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")
r4 <- plm(pasian ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")
r5 <- plm(pnhblk ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")
r6 <- plm(phisp ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")


table4_panel1 <- stargazer(ses1,ses2,ses3,ses4,ses5,
          type = "text",
          keep = c("divergence"),
          header = FALSE,
          no.space = TRUE,
          title = "",
          omit.stat = c("aic","adj.rsq"),
          star.cutoffs = c(0.05, 0.01, 0.001))

table4_panel2 <- stargazer(h1,h2,h3,h4,h5,
          type = "text",
          keep = c("divergence"),
          header = FALSE,
          no.space = TRUE,
          title = "",
          omit.stat = c("aic","adj.rsq"),
          star.cutoffs = c(0.05, 0.01, 0.001))                  

table4_panel3 <- stargazer(r8,r4,r5,r6,
          type = "text",
          keep = c("divergence"),
          header = FALSE,
          no.space = TRUE,
          title = "",
          omit.stat = c("aic","adj.rsq"),
          star.cutoffs = c(0.05, 0.01, 0.001))

```

## Table 5: Divergence and Sales
```{r table5}

df_sales <- read_csv(here::here("df_sales.csv")) 

m1 <- plm(divergence ~ co_ethnic + white_minority + minority_white + minority_minority + n_sales + pnhblk + phisp + pasian + pop + pown + pvac + p30old + INDIVIDUAL, data = df_sales, index = c("trtid10", "year_num"),
          model = "fd")

table5 <- stargazer(m1,
          type = "text",
          header = FALSE,
          no.space = TRUE,
          omit = c("INDIVIDUAL","n_sales","pown"),
          keep.stat = c("n","rsq"),
          title = "",
          star.cutoffs = c(0.05, 0.01, 0.001))

```

# Figures

```{r fig1}



df_mean <- df %>%
  filter(!is.na(divergence) & !is.na(year_num)) %>% 
  group_by(year_num) %>%
  summarise(mean_div = mean(divergence)) # Calculate year-specific mean to be included in each plot.

df %>% 
filter(!is.na(divergence) & !is.na(year_num)) %>% 
  ggplot(aes(x = divergence, group = year_num)) +
  geom_histogram(aes(y = ..density..), color="black", fill="white",
                 bins = 50) +
  geom_density() +
  geom_vline(data = df_mean, mapping = aes(xintercept = mean_div)) +
  theme_ipsum() + 
  theme(
    axis.title.y = element_text(hjust=0.5, size=18),
    axis.title.x = element_text(hjust=0.5, size=18),
  ) +
  ylab("Density") +
  xlab("Divergence Score") +
  facet_wrap(~year_num) +
  theme(
    legend.position="none",
    axis.ticks.x=element_blank(),
    text=element_text(size=21)
  ) + 
  labs(
    caption = "Vertical lines indicate year-specific mean of divergence."
  )


```

```{r fig2}

# Call in spatial data for SF County
sf <- tracts(state = "CA", county = "075",
             cb = TRUE,
             year = 2010) %>% 
  mutate(GEOID = paste0(STATE,COUNTY,TRACT))

# Make a separate df for each year
df90 <- df %>% 
  filter(year_num==1990) %>% 
  geo_join(sf, ., "GEOID", "trtid10") %>%  #join with spatial data 
  st_transform(merged,crs="WGS84") %>% 
  mutate(divergence = ifelse(is.na(divergence),
                                   median(divergence, na.rm = TRUE),
                                   divergence)) 

df00 <- df %>% 
  filter(year_num==2000) %>% 
  geo_join(sf, ., "GEOID", "trtid10") %>%  #join with spatial data 
  st_transform(merged,crs="WGS84") %>% 
  mutate(divergence = ifelse(is.na(divergence),
                                   median(divergence, na.rm = TRUE),
                                   divergence)) 

df12 <- df %>% 
  filter(year_num==2010) %>% 
  geo_join(sf, ., "GEOID", "trtid10") %>%  #join with spatial data 
  st_transform(merged,crs="WGS84") %>% 
  mutate(divergence = ifelse(is.na(divergence),
                                   median(divergence, na.rm = TRUE),
                                   divergence)) 

df17 <- df %>% 
  filter(year_num==2017) %>% 
  geo_join(sf, ., "GEOID", "trtid10") %>%  #join with spatial data 
  st_transform(merged,crs="WGS84") %>% 
    mutate(divergence = ifelse(is.na(divergence),
                                   median(divergence, na.rm = TRUE),
                                   divergence))
# Make plots:
p90 <- 
  ggplot() + 
  geom_sf(data = df90, aes(fill = divergence), size = 0.01) +
  scale_fill_distiller(type="seq", trans="reverse", palette = "Reds", 
                       breaks = c(0.1,0.8), labels = c("Low","High")
                       ) +
  theme_nothing(legend=TRUE) +
  labs(fill="Divergence Score")

p00 <- 
  ggplot() + 
  geom_sf(data = df00, aes(fill = divergence), size = 0.01) +
  scale_fill_distiller(type="seq", trans="reverse", palette = "Reds", 
                       breaks = c(0.1,0.8), labels = c("Low","High")
                       ) +
  theme_nothing(legend=TRUE) +
  labs(fill="Divergence Score")

p12 <- 
  ggplot() + 
  geom_sf(data = df12, aes(fill = divergence), size = 0.01) +
  scale_fill_distiller(type="seq", trans="reverse", palette = "Reds", 
                      breaks = c(0.03,0.4), labels = c("Low","High")
                       ) +
  theme_nothing(legend=TRUE) +
  labs(fill="Divergence Score")

p17 <- 
  ggplot() + 
  geom_sf(data = df17, aes(fill = divergence), size = 0.01) +
  scale_fill_distiller(type="seq", trans="reverse", palette = "Reds", 
                      breaks = c(0.03,0.4), labels = c("Low","High")
                      ) +
  theme_nothing(legend=TRUE) +
  labs(fill="Divergence Score")

combined <- ggpubr::ggarrange(p90,p00,p12,p17, ncol=2, nrow=2, common.legend = TRUE, 
                              legend = "right",
                  labels = c("1990",
                             "2000",
                             "2012",
                             "2017"
                        ))

```

```{r fig3}

# Create interactions of year/race:
total <- df %>% 
   select(trtid10,year_num,ends_with("share"),
         divergence,
         pnhblk,
         pnhwht,
         pasian,
         phisp) %>% 
  rename(
    White_owner = nhwht_share,
    White_resident = pnhwht,
    Black_owner = nhblk_share,
    Black_resident = pnhblk,
    Asian_owner = asian_share,
    Asian_resident = pasian,
    Hispanic_owner = hisp_share,
    Hispanic_resident = phisp
  ) %>%
  select(-other_share) %>%
  pivot_longer(
    -c("trtid10","year_num", "divergence"),
    names_sep = "_",
    names_to = c("race","type"),
    values_to = "share"
  )

total$race_int <- interaction(total$year_num, total$race)

# Define primary and secondary y-axis limits
ylim.prim <- c(0, 85) 
ylim.sec <- c(0, 0.9)   

# Calculate slope and intercept for secondary axis transformation
b <- diff(ylim.prim)/diff(ylim.sec)
a <- ylim.prim[1] - b*ylim.sec[1] 

# Plot for Fillmore 
g1 <- total %>% 
  filter(trtid10=="06075016100") %>% ## Fillmore
  ungroup() %>% 
  ggplot(aes(x = factor(race_int,
                        level = c(
                          "1990.White", "1990.Asian", "1990.Black", "1990.Hispanic",
                          "2000.White", "2000.Asian", "2000.Black", "2000.Hispanic",
                          "2010.White", "2010.Asian", "2010.Black", "2010.Hispanic",
                          "2017.White", "2017.Asian", "2017.Black", "2017.Hispanic"
                        )), y = share, fill = factor(type))) +
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_line(aes(y = a + divergence*b, group = 1), color = "red") +
  scale_y_continuous("Share", sec.axis = sec_axis(~ (. - a)/b, name = "Divergence")) +
  annotate("text", x = 1:16, y = -2, label = rep(c("W", "A", "B", "H"), 4)) +
  annotate("text", c(2.5, 6.5, 10.5, 14.5), y = -5, label = c("1990","2000","2010","2017")) +
  theme_minimal() +
  theme(plot.margin = unit(c(1, 1, 4, 1), "lines"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank()) +
  labs(
    fill = ""
  ) +
  scale_fill_hue(labels = c("Owners", "Residents")) +
  theme(text=element_text(size=20))

# Plot for South Beach 
g2 <- total %>% 
  filter(trtid10=="06075012100") %>% # South Beach
  ungroup() %>% 
  ggplot(aes(x = factor(race_int,
                        level = c(
                          "1990.White", "1990.Asian", "1990.Black", "1990.Hispanic",
                          "2000.White", "2000.Asian", "2000.Black", "2000.Hispanic",
                          "2010.White", "2010.Asian", "2010.Black", "2010.Hispanic",
                          "2017.White", "2017.Asian", "2017.Black", "2017.Hispanic"
                        )), y = share, fill = factor(type))) +
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_line(aes(y = a + divergence*b, group = 1), color = "red") +
  scale_y_continuous("Share", sec.axis = sec_axis(~ (. - a)/b, name = "Divergence")) +
  annotate("text", x = 1:16, y = -2, label = rep(c("W", "A", "B", "H"), 4)) +
  annotate("text", c(2.5, 6.5, 10.5, 14.5), y = -5, label = c("1990","2000","2010","2017")) +
  theme_minimal() +
  theme(plot.margin = unit(c(1, 1, 4, 1), "lines"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank()) +
  labs(
    fill = ""
  ) +
  scale_fill_hue(labels = c("Owners", "Residents")) +
  theme(text=element_text(size=20))

# Plot for Tenderloin 
g3 <- total %>% 
  filter(trtid10=="06075012401") %>% # Tenderloin
  ungroup() %>% 
  ggplot(aes(x = factor(race_int,
                        level = c(
                          "1990.White", "1990.Asian", "1990.Black", "1990.Hispanic",
                          "2000.White", "2000.Asian", "2000.Black", "2000.Hispanic",
                          "2010.White", "2010.Asian", "2010.Black", "2010.Hispanic",
                          "2017.White", "2017.Asian", "2017.Black", "2017.Hispanic"
                        )), y = share, fill = factor(type))) +
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_line(aes(y = a + divergence*b, group = 1), color = "red") +
  scale_y_continuous("Share", sec.axis = sec_axis(~ (. - a)/b, name = "Divergence")) +
  annotate("text", x = 1:16, y = -2, label = rep(c("W", "A", "B", "H"), 4)) +
  annotate("text", c(2.5, 6.5, 10.5, 14.5), y = -5, label = c("1990","2000","2010","2017")) +
  theme_minimal() +
  theme(plot.margin = unit(c(1, 1, 4, 1), "lines"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank()) +
  labs(
    fill = ""
  ) +
  scale_fill_hue(labels = c("Owners", "Residents")) +
  theme(text=element_text(size=20))

# Arrange plots in a grid
fig3 <- ggpubr::ggarrange(g1, g2, g3, ncol = 3, nrow = 1, common.legend = TRUE, 
                           legend = "bottom",
                           labels = c("Fillmore", "Union Square", "Tenderloin"),
                           font.label = list(size = 20))


```


