---
title: "sfp-tables"
author: "Nima Dahir"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
# This script generates all results in "Who Owns the Neighborhood? Ethnoracial Composition of Property Ownership and Neighborhood Trajectories in San Francisco" 

knitr::opts_chunk$set(warning = FALSE, message = FALSE) 

#Clean up environment
rm(list=ls())

#Packages
library(kableExtra)
library(stargazer)
library(ggplot2)
library(foreign)
library(tidycensus)
library(janitor)
library(tidyverse)
library(nnet)
library(data.table)
library(psych)
library(plm)
library(conflicted)

```

# Load Data

```{r data}
df <- read_csv(here::here("df_full.csv")) 

```

# Tables
## Table 1: Racial Compositions of Owners and Residents by Divergence

```{r table1}
  df %>% 
  mutate(divergence_quartile = ntile(divergence,4)) %>% # higher divergence, higher quartile
  dplyr::select(divergence_quartile,
                asian_share, # _shares are owner shares
                nhblk_share,
                hisp_share,
                nhwht_share,
                other_share,
                pnhwht, # resident shares
                pnhblk,
                phisp,
                pasian,
                pother) %>% 
  group_by(divergence_quartile) %>% 
  summarise(across(where(is.numeric),list(mean = mean)))
```

## Table 2: Descriptive Statistics of Neighborhood Characteristics in Dataset

```{r table 2}

table2 <- df %>% 
  select(year_num,
         hinc,
         pcol,
         punemp,
         pprof,
         pnhblk,
         pnhwht,
         pasian,
         phisp,
         mrent,
         pown,
         p30old,
         p10yrs,
         mhmval,
         divergence) %>% 
  group_by(year_num) %>%
  summarise(across(
    everything(),
    list(
      mean = ~mean(., na.rm = TRUE),
      sd = ~sd(., na.rm = TRUE)
    )
  ))

```

## Table 3: Divergence Score and Race Models

```{r table3}

# Begin by scaling divergence to interpret in standard deviations

scaled <- df %>% 
  group_by(year) %>% 
  mutate(across(where(is.numeric), ~ as.numeric(scale(.))))

# Divergence Cross-Sectional Models:
m1 <- plm(divergence ~ pnhblk + phisp + pasian + INDIVIDUAL + pown, model="within",index=c("trtid10","year"), effect = "time", data=scaled)

m2 <- plm(divergence ~ pnhblk + phisp + pasian + hinc + pop + pown + pvac + p30old + INDIVIDUAL, model="within",index=c("trtid10","year"), effect = "time", data=scaled)

# Foreign born:
m3 <- plm(divergence ~ pfb + pown + INDIVIDUAL, model="within",index=c("trtid10","year"), effect = "time", data=scaled)

m4 <-plm(divergence ~ pfb + pnhblk + phisp + hinc + pop + pown + pvac + p30old + INDIVIDUAL, model="within",index=c("trtid10","year"), effect = "time", data=scaled)

# Asian:
m5 <- plm(divergence ~ pasian +
            hinc + pop + pown  + pvac + p30old + INDIVIDUAL, model="within",index=c("trtid10","year"), effect = "time", data=scaled)

# Divergence Cross-Sectional Model with Interactions

m6 <- plm(divergence ~ pnhblk*pfb + phisp*pfb + 
                     hinc + pop + pown  + pvac + p30old + INDIVIDUAL, model="within",index=c("trtid10","year"), effect = "time", data=scaled)

stargazer(m1,m2,m3,m4,m5,m6,
                    type = "text",
                    omit = c("factor\\(year", "factor\\(trtid10", "Constant", "INDIVIDUAL"),
                    header = FALSE,
                    no.space = TRUE,
                    dep.var.labels = "Divergence Score",
                    title = "Race, Foreign Born",
                    keep.stat = c("n","rsq"),
                    notes = c("All models include year fixed effects and control for the number of individually-owned properties in each tract.","All variables are standardized to a mean of zero and standard deviation of 1; thus, coefficients can be interpreted as expected standard deviation changes in divergence with one standard deviation change in each independent variable."),
                    notes.align = "l",
                    star.cutoffs = c(0.05, 0.01, 0.001))
```


## Table 4: Divergence and Neighborhood Change

```{r table4}

library(plm)

# Create Analytic Sample for these models:
ses <- scaled %>% 
  filter(!is.na(pcol) & !is.na(punemp) & !is.na(ppov) & !is.na(hinc) & !is.na(pprof)) %>% 
  filter(!is.na(mrent) & !is.na(pown) & !is.na(p30old) & !is.na(p10yrs) & !is.na(pvac) & !is.na(mhmval)) 


# Panel 1: SES Variables
ses1 <- plm(pcol ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pnhblk) + plm::lag(phisp) + plm::lag(pasian) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")
ses2 <- plm(punemp ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pnhblk) + plm::lag(phisp) + plm::lag(pasian) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")
ses3 <- plm(ppov ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pnhblk) + plm::lag(phisp) + plm::lag(pasian) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")
ses4 <- plm(hinc ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pnhblk) + plm::lag(phisp) + plm::lag(pasian) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")
ses5 <- plm(pprof ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pnhblk) + plm::lag(phisp) + plm::lag(pasian) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")

# Panel 2: Housing Variables

h1 <- plm(mrent ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pnhblk) + plm::lag(phisp) + plm::lag(pasian) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")
h2 <- plm(pown ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pnhblk) + plm::lag(phisp) + plm::lag(pasian) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")
h3 <- plm(p30old ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pnhblk) + plm::lag(phisp) + plm::lag(pasian) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")
h4 <- plm(p10yrs ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pnhblk) + plm::lag(phisp) + plm::lag(pasian) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")
h5 <- plm(mhmval ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pnhblk) + plm::lag(phisp) + plm::lag(pasian) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")

# Panel 3: Race

r8 <- plm(pnhwht ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")
r4 <- plm(pasian ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")
r5 <- plm(pnhblk ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")
r6 <- plm(phisp ~ plm::lag(divergence) + plm::lag(pown) + plm::lag(pop) + plm::lag(pvac) + plm::lag(p30old) + plm::lag(INDIVIDUAL), data = ses, index = c("trtid10", "year"), model = "within", effect = "twoways")


table4_panel1 <- stargazer(ses1,ses2,ses3,ses4,ses5,
          type = "text",
          keep = c("divergence"),
          header = FALSE,
          no.space = TRUE,
          title = "",
          omit.stat = c("aic","adj.rsq"),
          star.cutoffs = c(0.05, 0.01, 0.001))

table4_panel2 <- stargazer(h1,h2,h3,h4,h5,
          type = "text",
          keep = c("divergence"),
          header = FALSE,
          no.space = TRUE,
          title = "",
          omit.stat = c("aic","adj.rsq"),
          star.cutoffs = c(0.05, 0.01, 0.001))                  

table4_panel3 <- stargazer(r8,r4,r5,r6,
          type = "text",
          keep = c("divergence"),
          header = FALSE,
          no.space = TRUE,
          title = "",
          omit.stat = c("aic","adj.rsq"),
          star.cutoffs = c(0.05, 0.01, 0.001))

```

## Table 5: Divergence and Sales
```{r table5}

df_sales <- read_csv(here::here("df_sales.csv")) 

m1 <- plm(divergence ~ co_ethnic + white_minority + minority_white + minority_minority + n_sales + pnhblk + phisp + pasian + pop + pown + pvac + p30old + INDIVIDUAL, data = df_sales, index = c("trtid10", "year_num"),
          model = "fd")

table5 <- stargazer(m1,
          type = "text",
          header = FALSE,
          no.space = TRUE,
          omit = c("INDIVIDUAL","n_sales","pown"),
          keep.stat = c("n","rsq"),
          title = "",
          star.cutoffs = c(0.05, 0.01, 0.001))

```

